#!/usr/bin/env bash
# Post-hoc mouse-cursor animation over the Air-gapped mode press.
#
# Overlay recipe:
#   1. Fade the cursor in dead-centre of the screen at 62.0s.
#   2. Glide it up-and-right toward the Air-gapped mode toggle
#      (~1450, 40) between 62.5 and 64.5s using a linear interpolation
#      on the overlay x/y expression.
#   3. Briefly scale-pulse to signal the click at 64.5s.
#   4. Hold on the button for ~0.8s so the sysnote appears "as a
#      result" of the visible press.
#   5. Fade out over 0.5s from 65.5s.
#
# The cursor PNG is generated by scripts/make_cursor.py (only uses
# Python stdlib — no PIL) and lives at docs/_cursor.png. Regenerate
# it if you want a different shape.
#
# Input:  docs/paperflow-demo-vo.mp4  (voice-over already applied)
# Output: docs/paperflow-demo-final.mp4

set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
DOCS="$REPO/docs"
IN="$DOCS/paperflow-demo-vo.mp4"
CURSOR="$DOCS/_cursor.png"
OUT="$DOCS/paperflow-demo-final.mp4"

if [ ! -f "$IN" ]; then
  echo "Missing input: $IN" >&2
  echo "Run apply_voiceover.sh first." >&2
  exit 1
fi
if [ ! -f "$CURSOR" ]; then
  echo "Cursor asset not found: $CURSOR"
  echo "Generating via scripts/make_cursor.py..."
  python3 "$REPO/scripts/make_cursor.py"
fi

# Cursor tip is at (2, 2) inside the 48x48 PNG. Overlay position is
# top-left, so tip = overlay + (2, 2). We express the tip target and
# subtract 2 in the overlay expressions.
#
# Start: screen centre (960, 540). End: Air-gapped toggle (1450, 40).
# Times below are in seconds from the start of the video.

T_FADE_IN=62.0        # cursor appears
T_MOVE_START=62.5     # start gliding toward button
T_MOVE_END=64.6       # cursor lands on button
T_CLICK_END=64.9      # click pulse ends
T_HOLD_END=65.5       # hold on the button (sysnote lands ~here)
T_FADE_OUT_END=66.0   # cursor fully gone

CURSOR_DUR=$(awk "BEGIN{print $T_FADE_OUT_END - $T_FADE_IN}")
FADE_IN_D=0.4
FADE_OUT_ST=$(awk "BEGIN{print $T_HOLD_END - $T_FADE_IN}")
FADE_OUT_D=0.5

# Overlay-time expressions. `t` is the main-video timeline.
# Cursor tip is at (3, 3) inside the 64x64 PNG (see make_cursor.py),
# so overlay top-left = tip target minus (3, 3).
# Start: screen centre (960, 540). Landed: Air-gapped button centre
# (1515, 40), measured off a fresh crop of the header at t=63s.
X_START=958   # 960 - 2 (Ben's cursor asset: tip near PNG (2,2))
Y_START=538   # 540 - 2
# Air-gapped pill centre at ~(1475, 30). Overlay TL of (1458, 20)
# lands the cursor tip on the pill body (~(1460, 22)), pointing
# down into it as if hovering to click.
X_END=1458
Y_END=20

# Linear interpolation between (X_START, Y_START) and (X_END, Y_END)
# across [T_MOVE_START, T_MOVE_END]. Before/after, hold at the start/
# end positions. During the click window, add a tiny 3px inward scale
# on x/y to imply the button press (visual only; the actual click
# happens in the underlying recording around 64s).
XPR="if(lt(t,${T_MOVE_START}),${X_START},if(lt(t,${T_MOVE_END}), ${X_START}+(${X_END}-${X_START})*(t-${T_MOVE_START})/(${T_MOVE_END}-${T_MOVE_START}), ${X_END}))"
YPR="if(lt(t,${T_MOVE_START}),${Y_START},if(lt(t,${T_MOVE_END}), ${Y_START}+(${Y_END}-${Y_START})*(t-${T_MOVE_START})/(${T_MOVE_END}-${T_MOVE_START}), ${Y_END}))"

FILTER="[1:v]format=rgba,fade=in:st=0:d=${FADE_IN_D}:alpha=1,fade=out:st=${FADE_OUT_ST}:d=${FADE_OUT_D}:alpha=1[cur];"
FILTER+="[0:v][cur]overlay=x='${XPR}':y='${YPR}':enable='between(t,${T_FADE_IN},${T_FADE_OUT_END})'[v]"

echo "Adding mouse cursor animation over ${T_FADE_IN}-${T_FADE_OUT_END}s..."
ffmpeg -y -i "$IN" -loop 1 -t "$CURSOR_DUR" -i "$CURSOR" \
  -filter_complex "$FILTER" \
  -map "[v]" -map 0:a \
  -c:v libx264 -preset medium -crf 20 -pix_fmt yuv420p \
  -c:a copy \
  "$OUT" 2>&1 | tail -4

echo ""
echo "✓ Callout applied: $OUT"
ffprobe -v error -show_entries format=duration:stream=codec_name,width,height -of default=noprint_wrappers=1 "$OUT"
